apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: brownbag-deployment
  name: brownbag-configmap
data:
  config.txt: k8s config

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: brownbag-secret
  labels:
    app: brownbag-deployment
data:
  secret.txt: c3VwZXIgc2VjcmV0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: brownbag-deployment
  labels:
    app: brownbag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brownbag-deployment
  template:
    metadata:
      labels:
        app: brownbag-deployment
    spec:
      containers:
      - name: server
        image: centos:centos7
        ports:
        - containerPort: 8000
        command: ['python', '-m', 'SimpleHTTPServer']
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /config.txt
          subPath: config.txt
        - name: secret-volume
          subPath: secret.txt
          mountPath: "/secret.txt"
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: brownbag-configmap
      - name: secret-volume
        secret:
          secretName: brownbag-secret


